# Generated by Django 5.0.2 on 2024-03-04 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='ingredientKey',
            new_name='ingredient_key',
        ),
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='recipeKey',
            new_name='recipe_key',
        ),
    ]
